//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BonVoyage_TravelAgency.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BonVoyage_TravelAgency.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Bon Voyage Company.
        /// </summary>
        public static string About_Bon_Voyage_Company {
            get {
                return ResourceManager.GetString("About_Bon_Voyage_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Bon Voyage.
        /// </summary>
        public static string About_BonVoyage {
            get {
                return ResourceManager.GetString("About_BonVoyage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string About_Us {
            get {
                return ResourceManager.GetString("About_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All charter flights.
        /// </summary>
        public static string All_charter_flights {
            get {
                return ResourceManager.GetString("All_charter_flights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All countries of the world.
        /// </summary>
        public static string All_countries_of_the_world {
            get {
                return ResourceManager.GetString("All_countries_of_the_world", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All users.
        /// </summary>
        public static string All_users {
            get {
                return ResourceManager.GetString("All_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autumn tours.
        /// </summary>
        public static string Autumn_tours {
            get {
                return ResourceManager.GetString("Autumn_tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charters.
        /// </summary>
        public static string Charters {
            get {
                return ResourceManager.GetString("Charters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charters to Bulgaria.
        /// </summary>
        public static string Charters_to_Bulgaria {
            get {
                return ResourceManager.GetString("Charters_to_Bulgaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charters to Egypt.
        /// </summary>
        public static string Charters_to_Egypt {
            get {
                return ResourceManager.GetString("Charters_to_Egypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charters to Greece.
        /// </summary>
        public static string Charters_to_Greece {
            get {
                return ResourceManager.GetString("Charters_to_Greece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charters to Montenegro.
        /// </summary>
        public static string Charters_to_Montenegro {
            get {
                return ResourceManager.GetString("Charters_to_Montenegro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charters to Turkey.
        /// </summary>
        public static string Charters_to_Turkey {
            get {
                return ResourceManager.GetString("Charters_to_Turkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat room.
        /// </summary>
        public static string Chat_room {
            get {
                return ResourceManager.GetString("Chat_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coronavirus tests.
        /// </summary>
        public static string Coronavirus_tests {
            get {
                return ResourceManager.GetString("Coronavirus_tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover our discounted tours and best deals.
        /// </summary>
        public static string Discover_our_discounted_tours_and_best_deals {
            get {
                return ResourceManager.GetString("Discover_our_discounted_tours_and_best_deals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to chat room.
        /// </summary>
        public static string Go_to_Chat_Room {
            get {
                return ResourceManager.GetString("Go_to_Chat_Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide.
        /// </summary>
        public static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to book a tour.
        /// </summary>
        public static string How_to_book_a_tour {
            get {
                return ResourceManager.GetString("How_to_book_a_tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to pay for the tour.
        /// </summary>
        public static string How_to_pay_for_the_tour {
            get {
                return ResourceManager.GetString("How_to_pay_for_the_tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Minute Tours.
        /// </summary>
        public static string Last_Minute_Tours {
            get {
                return ResourceManager.GetString("Last_Minute_Tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string Learn_More {
            get {
                return ResourceManager.GetString("Learn_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal information.
        /// </summary>
        public static string Legal_information {
            get {
                return ResourceManager.GetString("Legal_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My contacts.
        /// </summary>
        public static string My_contacts {
            get {
                return ResourceManager.GetString("My_contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New year tours.
        /// </summary>
        public static string New_year_tours {
            get {
                return ResourceManager.GetString("New_year_tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of persons.
        /// </summary>
        public static string Number_of_persons {
            get {
                return ResourceManager.GetString("Number_of_persons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office addresses.
        /// </summary>
        public static string Office_addresses {
            get {
                return ResourceManager.GetString("Office_addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package tours.
        /// </summary>
        public static string Package_tours {
            get {
                return ResourceManager.GetString("Package_tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confirm.
        /// </summary>
        public static string Password_Confirm {
            get {
                return ResourceManager.GetString("Password_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        public static string Preference {
            get {
                return ResourceManager.GetString("Preference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string Privacy_Policy {
            get {
                return ResourceManager.GetString("Privacy_Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        public static string Refund {
            get {
                return ResourceManager.GetString("Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews from tourists.
        /// </summary>
        public static string Reviews_from_tourists {
            get {
                return ResourceManager.GetString("Reviews_from_tourists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Tours.
        /// </summary>
        public static string Search_Tours {
            get {
                return ResourceManager.GetString("Search_Tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send your message.
        /// </summary>
        public static string Send_your_message {
            get {
                return ResourceManager.GetString("Send_your_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ski tours.
        /// </summary>
        public static string Ski_tours {
            get {
                return ResourceManager.GetString("Ski_tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring tours.
        /// </summary>
        public static string Spring_tours {
            get {
                return ResourceManager.GetString("Spring_tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stages of booking a tour.
        /// </summary>
        public static string Stages_of_booking_a_tour {
            get {
                return ResourceManager.GetString("Stages_of_booking_a_tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summer tours.
        /// </summary>
        public static string Summer_tours {
            get {
                return ResourceManager.GetString("Summer_tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips for tourists.
        /// </summary>
        public static string Tips_for_tourists {
            get {
                return ResourceManager.GetString("Tips_for_tourists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour booking.
        /// </summary>
        public static string Tour_booking {
            get {
                return ResourceManager.GetString("Tour_booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tours.
        /// </summary>
        public static string Tours {
            get {
                return ResourceManager.GetString("Tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tours to Croitia.
        /// </summary>
        public static string Tours_to_Croitia {
            get {
                return ResourceManager.GetString("Tours_to_Croitia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tours to Egypt.
        /// </summary>
        public static string Tours_to_Egypt {
            get {
                return ResourceManager.GetString("Tours_to_Egypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tours to Greece.
        /// </summary>
        public static string Tours_to_Greece {
            get {
                return ResourceManager.GetString("Tours_to_Greece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tours to Montenegro.
        /// </summary>
        public static string Tours_to_Montenegro {
            get {
                return ResourceManager.GetString("Tours_to_Montenegro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tours to Spain.
        /// </summary>
        public static string Tours_to_Spain {
            get {
                return ResourceManager.GetString("Tours_to_Spain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tours to Turkey.
        /// </summary>
        public static string Tours_to_Turkey {
            get {
                return ResourceManager.GetString("Tours_to_Turkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel agencies in Bordeaux.
        /// </summary>
        public static string Travel_agencies_in_Bordeaux {
            get {
                return ResourceManager.GetString("Travel_agencies_in_Bordeaux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel agencies in Lyon.
        /// </summary>
        public static string Travel_agencies_in_Lyon {
            get {
                return ResourceManager.GetString("Travel_agencies_in_Lyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel agencies in Marseilles.
        /// </summary>
        public static string Travel_agencies_in_Marseilles {
            get {
                return ResourceManager.GetString("Travel_agencies_in_Marseilles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel agencies in Nice.
        /// </summary>
        public static string Travel_agencies_in_Nice {
            get {
                return ResourceManager.GetString("Travel_agencies_in_Nice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel agencies in Paris.
        /// </summary>
        public static string Travel_agencies_in_Paris {
            get {
                return ResourceManager.GetString("Travel_agencies_in_Paris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel insurance.
        /// </summary>
        public static string Travel_insurance {
            get {
                return ResourceManager.GetString("Travel_insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel news.
        /// </summary>
        public static string Travel_news {
            get {
                return ResourceManager.GetString("Travel_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserSurname.
        /// </summary>
        public static string UserSurname {
            get {
                return ResourceManager.GetString("UserSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string View_Details {
            get {
                return ResourceManager.GetString("View_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WelcomeToBonVoyage.
        /// </summary>
        public static string WelcomeToBonVoyage {
            get {
                return ResourceManager.GetString("WelcomeToBonVoyage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to buy.
        /// </summary>
        public static string Where_to_buy {
            get {
                return ResourceManager.GetString("Where_to_buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to go for a tourist.
        /// </summary>
        public static string Where_to_go_for_a_tourist {
            get {
                return ResourceManager.GetString("Where_to_go_for_a_tourist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why do people trust us? .
        /// </summary>
        public static string Why_do_people_trust_us {
            get {
                return ResourceManager.GetString("Why_do_people_trust_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter tours.
        /// </summary>
        public static string Winter_tours {
            get {
                return ResourceManager.GetString("Winter_tours", resourceCulture);
            }
        }
    }
}
